# Generated by Django 4.2.10 on 2024-07-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_app', '0005_customuser_stripe_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
    ]
