# Generated by Django 4.2.10 on 2024-07-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_app', '0009_selfintroduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfintroduction',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像'),
        ),
    ]
